### ISSUE TITLE
fix UI while displaying actions

### ISSUE THREAD

**Issue by lolo8304** [cordalo-ch/cordalo-template#6]
since the change from Enum to objects the String representation is not correct anxymore. checkout the bean for this

<img width="967" alt="Screenshot 2019-11-25 09 48 19" src="https://user-images.githubusercontent.com/5243791/69525662-e585fb80-0f68-11ea-81bc-4d34612cc462.png">

**Comment by cedricwalter** [comment]
solved in cordalo
